salesforce_sfdx/main/default/objects/IMS_Menu__mdt/IMS_Menu__mdt.object-meta.xml
<CustomObject>
    <description>IMS Menu User both GRS&amp;GLH</description>
    <label>IMS Menu</label>
    <pluralLabel>IMS Menus</pluralLabel>
</CustomObject>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/French_Label__c.field-meta.xml
<CustomField>
    <fullName>French_Label__c</fullName>
    <description>IMS Menu French Label Value</description>
    <label>French Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/Menu_Order__c.field-meta.xml
<CustomField>
    <fullName>Menu_Order__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Menu Order based on Main and Sub Menu</description>
    <inlineHelpText>Give a order based on parentId and Count of Submenu Count</inlineHelpText>
    <label>Menu Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/Parent_Menu__c.field-meta.xml
<CustomField>
    <fullName>Parent_Menu__c</fullName>
    <defaultValue>'HEAD'</defaultValue>
    <description>Parent menu value</description>
    <inlineHelpText>Give a Parent menu value as a key to add to menu layer</inlineHelpText>
    <label>Parent Menu</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/submenu_count__c.field-meta.xml
<CustomField>
    <fullName>submenu_count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>IMS Submenu Postion</description>
    <inlineHelpText>Give how many sub menus will be added, 0- Will be consider no Submenu</inlineHelpText>
    <label>submenu count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <description>Menu URL</description>
    <label>url</label>
    <type>Url</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_Menu__mdt/fields/UserType__c.field-meta.xml
<CustomField>
    <fullName>UserType__c</fullName>
    <description>IMS Menu User types</description>
    <label>UserType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GLH</fullName>
            </value>
            <value>
                <fullName>GRS</fullName>
            </value>
            <value>
                <fullName>Combo</fullName>
                <default>true</default>
                <label>Combo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/classes/IMSCommunityHelper.cls
/*********************************************************************************************
*   Class: IMSCommunityHelper
*   Purpose: Helper class for methods used across IMS Community
*   
*   @ChangeLog
*   Date        User                 Description
*   2019-05-11  Kuldeep Chauhan      Initial Implementation
**********************************************************************************************/
global class IMSCommunityHelper implements vlocity_ins.VlocityOpenInterface {
public Boolean InvokeMethod(
    String methodName,
    Map<String,Object> input,
    Map<String,Object> output,
    Map<String,Object> options) {
    if (methodName=='getCurrentUserType') {
        
        // Delegated to another method or a helper class
        /*
        if(UserInfo.getName().containsIgnoreCase('GLH'))
            output.put('UserType','GLH');
        else if(UserInfo.getName().containsIgnoreCase('GRS'))
            output.put('UserType','GRS');
        else
            output.put('UserType','Combo');*/
        getCurrentUserType(output);
    }
    return Boolean.valueOf('TRUE');   
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,Object> getCurrentUserType(Map<String,Object> output){
        
        if(output==NULL)
            output = new Map<String,Object>();
        if(UserInfo.getName().containsIgnoreCase('GLH'))
            output.put('UserType','GLH');
        else if(UserInfo.getName().containsIgnoreCase('GRS'))
            output.put('UserType','GRS');
        else
            output.put('UserType','Combo');
        return output;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, IMS_Menu__mdt> getMenuList() {
        String key = '';
        if(UserInfo.getName().containsIgnoreCase('GLH')){
            key = 'GLH';
        }else if(UserInfo.getName().containsIgnoreCase('GRS')){
            key = 'GRS';
        }else{
            key = 'Combo';
        }        
            
        List<IMS_Menu__mdt> lstMenu = [SELECT QualifiedApiName,Label,French_Label__c,MasterLabel,Menu_Order__c,Parent_Menu__c,submenu_count__c,url__c,UserType__c 
        FROM IMS_Menu__mdt WHERE UserType__c =: key];
        
        System.Debug('RRR ' + lstMenu);
        Map<String, IMS_Menu__mdt> menuHead = new Map<String, IMS_Menu__mdt>();
        //Map<String, IMS_Menu__mdt> menuSubHead = new Map<String, IMS_Menu__mdt>();
        List<mainMenu> mm = new List<mainMenu>();
        for(IMS_Menu__mdt tempJA : lstMenu){
            if(tempJA.Parent_Menu__c == 'HEAD'){         
                menuHead.put(tempJA.QualifiedApiName,tempJA);
            }else{
                menuHead.put(tempJA.Parent_Menu__c,tempJA);
            }            
        } 
		system.debug('@@@Map@@@'+menuHead); 
        return menuHead;
    } 

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactList() {
        return [
            SELECT Id, Name, Title, Phone, Email
            FROM Contact
            WHERE Name != null
            WITH SECURITY_ENFORCED
            LIMIT 10
        ];
    }
    
    public class mainMenu { 
        public String title {get;set;} 
        public String url {get;set;} 
        public String icon {get;set;} 
        public Integer order {get;set;} 
        public String parentId {get;set;} 
        public Integer childCount {get;set;}
        public List<subMenu> children{get;set;}        
    } 
    
    public class subMenu { 
        public String title {get;set;} 
        public String url {get;set;} 
        public String icon {get;set;} 
        public Integer order {get;set;} 
        public String parentId {get;set;} 
        public Integer childCount {get;set;}      
    }    

}