salesforce_sfdx/main/default/objects/IMS_English_Menu__c/IMS_English_Menu__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IMS User Menus Only English</description>
    <label>IMS English Menu</label>
</CustomObject>

salesforce_sfdx/main/default/objects/IMS_English_Menu__c/fields/Menu_Label__c.field-meta.xml
<CustomField>
    <fullName>Menu_Label__c</fullName>
    <description>IMS Menu Labels</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Give a Specifc English Labels</inlineHelpText>
    <label>Menu Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_English_Menu__c/fields/Menu_Order__c.field-meta.xml
<CustomField>
    <fullName>Menu_Order__c</fullName>
    <description>IMS Menu Order of alignment</description>
    <inlineHelpText>Give what order menu should display</inlineHelpText>
    <label>Menu Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_English_Menu__c/fields/Menu_Type__c.field-meta.xml
<CustomField>
    <fullName>Menu_Type__c</fullName>
    <description>Type of IMS menu ex. Profile,Main Menu etc.,</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Type of IMS menu ex. Profile,Main Menu etc.,</inlineHelpText>
    <label>Menu User</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/IMS_English_Menu__c/fields/Menu_URL__c.field-meta.xml
<CustomField>
    <fullName>Menu_URL__c</fullName>
    <description>IMS Menu Navigation URL</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Give a wrapper URL</inlineHelpText>
    <label>Menu URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/classes/currentUserInfoCtrl.cls
public with sharing class currentUserInfoCtrl {
   @AuraEnabled 
    public static user fetchUser(){
     // query current user information  
      User oUser = [select id,Name,TimeZoneSidKey,Username,Alias,Country,Email,FirstName,LastName,IsActive,IsPortalEnabled 
                 FROM User Where id =: userInfo.getUserId()];
        return oUser;
    }
    
    @auraEnabled
    public static List<IMS_English_Menu__c> fetchUserProfileMenu(){        
        List<IMS_English_Menu__c> Profilemenu =  [SELECT Menu_Order__c, Menu_Label__c, Menu_URL__c FROM IMS_English_Menu__c WHERE Menu_Type__c='Profile' ORDER BY Menu_Order__c];
		//inputs.add('Account Info', 'identity/s/settings/'+userInfo.getUserId());
        /*if(){
            
        }else if(){
            
        }*/        
        return Profilemenu;
    }
}